nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        host: blocbeta.com
        schemes: [https]

        info:
            title: BlocBeta
            description: BlocBeta API documentation
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: https
                    scheme: bearer
                    bearerFormat: JWT

        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
                prefix: Bearer

        security:
            - Bearer: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/documentation$) # Accepts routes under /api except /api/doc
