version: "3.1"
services:
  php-fpm:
    working_dir: /var/www
    build: _docker/php-fpm
    ports:
      - "9002:9000"
    volumes:
      - ./:/var/www:cached

  nginx:
    working_dir: /var/www
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www:cached
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./var/data/blocbeta/db:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blocbeta
      POSTGRES_PASSWORD: blocbeta
      POSTGRES_USER: blocbeta

  mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: ${JWT_PASSPHRASE}
      DEMO: 1
      ALLOW_ANONYMOUS: 1
      CORS_ALLOWED_ORIGINS: "*"
      PUBLISH_ALLOWED_ORIGINS: "*"
      DEBUG: 1
    ports:
      - "9090:80"

  redis:
    image: redis:alpine