version: "3.1"
services:
  php-fpm:
    working_dir: /var/www
    build: _docker/php-fpm
    ports:
      - "9002:9000"
    volumes:
      - ./:/var/www:cached

  nginx:
    working_dir: /var/www
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      VIRTUAL_HOST: blocbeta.com
      VIRTUAL_PORT: 80
    volumes:
      - ./:/var/www:cached
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    external:
      name: nginx-proxy